
2024-04-02 20:46:26,964 - __main__ - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/workspaces/DODcicd/main.py", line 134, in <module>
    def InferencePass(filename, model=LoadModel()):
  File "/workspaces/DODcicd/main.py", line 118, in LoadModel
    model = torch.load(
  File "/home/vscode/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/vscode/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/vscode/venv/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'ObjectDetectorV0' on <module '__main__' from '/workspaces/DODcicd/main.py'>
2024-04-02 20:59:01,159 - __main__ - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/workspaces/DODcicd/main.py", line 134, in <module>
    def InferencePass(filename, model=LoadModel()):
  File "/workspaces/DODcicd/main.py", line 120, in LoadModel
    ).to(params.params["device"])
AttributeError: '_IncompatibleKeys' object has no attribute 'to'
